-- Proyecto 1: cafeterias PUJ
-- Script unico para Oracle SQL Developer (ejecutar con F5)

SET DEFINE OFF
SET SERVEROUTPUT ON

--------------------------------------------------------------------------------
-- 1. LIMPIEZA SEGURA
--------------------------------------------------------------------------------
DECLARE
    PROCEDURE borrar_tabla(nombre_tabla VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE
            'DROP TABLE ' || nombre_tabla || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -942 THEN
                RAISE;
            END IF;
    END;
BEGIN
    -- Primero se eliminan las tablas hijas y luego las tablas padre.
    borrar_tabla('META');
    borrar_tabla('CAFETERIA');
    borrar_tabla('PISO');
    borrar_tabla('COLABORADOR');
    borrar_tabla('EDIFICIO');
END;
/

--------------------------------------------------------------------------------
-- 2. TABLAS
--------------------------------------------------------------------------------
CREATE TABLE edificio (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_edificio PRIMARY KEY (id),
    CONSTRAINT uq_edificio_nombre UNIQUE (nombre)
);

CREATE TABLE piso (
    id          NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    numeropiso  NUMBER(10,0) NOT NULL,
    idedificio  NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_piso PRIMARY KEY (id),
    CONSTRAINT uq_piso_natural UNIQUE (numeropiso, idedificio),
    CONSTRAINT fk_piso_edificio FOREIGN KEY (idedificio) REFERENCES edificio (id),
    CONSTRAINT ck_piso_numero CHECK (numeropiso >= 1)
);

CREATE TABLE cafeteria (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255) NOT NULL,
    idpiso  NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_cafeteria PRIMARY KEY (id),
    CONSTRAINT uq_cafeteria_nombre UNIQUE (nombre),
    CONSTRAINT fk_cafeteria_piso FOREIGN KEY (idpiso) REFERENCES piso (id)
);

CREATE TABLE colaborador (
    id               NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(255) NOT NULL,
    tipodocumento    VARCHAR2(255) NOT NULL,
    numerodocumento  NUMBER(10,0) NOT NULL,
    vinculacion      VARCHAR2(255) NOT NULL,
    comision         NUMBER(10,0) DEFAULT 10 NOT NULL,
    CONSTRAINT pk_colaborador PRIMARY KEY (id),
    CONSTRAINT uq_colaborador_documento UNIQUE (tipodocumento, numerodocumento),
    CONSTRAINT ck_colaborador_vinculacion CHECK (vinculacion IN ('PLANTA', 'TEMPORAL')),
    CONSTRAINT ck_colaborador_comision CHECK (comision BETWEEN 0 AND 100)
);

CREATE TABLE meta (
    id             NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    fechameta      DATE NOT NULL,
    valormeta      NUMBER(12,0) DEFAULT 0 NOT NULL,
    valorreal      NUMBER(12,0) DEFAULT 0 NOT NULL,
    idcafeteria    NUMBER(10,0) NOT NULL,
    idcolaborador  NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_meta PRIMARY KEY (id),
    CONSTRAINT uq_meta_natural UNIQUE (idcolaborador, idcafeteria, fechameta),
    CONSTRAINT fk_meta_cafeteria FOREIGN KEY (idcafeteria) REFERENCES cafeteria (id),
    CONSTRAINT fk_meta_colaborador FOREIGN KEY (idcolaborador) REFERENCES colaborador (id),
    CONSTRAINT ck_meta_valormeta CHECK (valormeta >= 0),
    CONSTRAINT ck_meta_valorreal CHECK (valorreal >= 0)
);

-- Indices para acelerar las relaciones y consultas por fecha.
CREATE INDEX ix_piso_edificio    ON piso (idedificio);
CREATE INDEX ix_cafeteria_piso   ON cafeteria (idpiso);
CREATE INDEX ix_meta_cafeteria   ON meta (idcafeteria);
CREATE INDEX ix_meta_colaborador ON meta (idcolaborador);
CREATE INDEX ix_meta_fecha       ON meta (fechameta);

--------------------------------------------------------------------------------
-- 3. DATOS
--------------------------------------------------------------------------------
DECLARE
    TYPE lista_texto IS TABLE OF VARCHAR2(255);
    TYPE lista_numero IS TABLE OF PLS_INTEGER;

    edificios lista_texto := lista_texto(
        'Barón', 'Giraldo', 'Fernando Barón', 'Emilio Arango',
        'José Rafael Arboleda', 'Jesús María Fernández', 'Rafael Arboleda',
        'Pedro Arrupe', 'Angel Valtierra', 'Carlos Ortiz', 'Félix Restrepo',
        'Manuel Briceño', 'Gabriel Giraldo', 'Jorge Hoyos', 'Juan XXIII',
        'Rafael Barrientos', 'Luis Carlos Galán', 'Fernando Barón Norte',
        'Biblioteca Alfonso Borrero', 'Rectoría', 'Ciencias Básicas',
        'Ingeniería', 'Medicina', 'Odontología', 'Enfermería',
        'Ciencias Jurídicas', 'Ciencias Económicas', 'Comunicación y Lenguaje',
        'Filosofía', 'Teología', 'Artes', 'Psicología', 'Arquitectura',
        'Laboratorios Norte', 'Laboratorios Sur', 'Deportes', 'Bienestar',
        'Auditorio Marino Troncoso', 'Centro Ático', 'Parqueadero Central'
    );

    cafeterias lista_texto := lista_texto(
        'Cafetería Central', 'Cafetería Los Cerezos', 'Cafetería El Jardín',
        'Cafetería La Terraza', 'Cafetería Punto Verde', 'Cafetería Express Norte',
        'Cafetería Biblioteca', 'Cafetería Ingeniería', 'Cafetería Ingeniería 4',
        'Cafetería Medicina', 'Cafetería Deportes', 'Cafetería Ático'
    );
    edificio_cafeteria lista_numero := lista_numero(1, 1, 2, 4, 6, 12, 19, 22, 22, 23, 36, 39);
    piso_cafeteria     lista_numero := lista_numero(1, 3, 1, 2, 1, 1, 2, 1, 4, 1, 1, 2);

    colaboradores lista_texto := lista_texto(
        'Ana María Rodríguez', 'Carlos Alberto Pérez', 'Diana Sofía Ramírez',
        'Jorge Enrique Moreno', 'Laura Catalina Gómez', 'Miguel Ángel Torres',
        'Paula Andrea Castro', 'Andrés Felipe Vargas', 'Sandra Milena Ruiz',
        'Julián David Herrera', 'Natalia Restrepo', 'Óscar Iván Suárez',
        'Claudia Patricia León', 'Ricardo Alonso Mejía', 'Mónica Alejandra Peña',
        'Fernando José Cárdenas', 'Adriana Lucía Ospina', 'Camilo Ernesto Rojas',
        'Gloria Esperanza Niño', 'Héctor Mauricio Salazar',
        'Liliana Beatriz Cortés', 'Sebastián Quintero', 'Yolanda Marcela Pineda',
        'Alejandro Bermúdez', 'Verónica Isabel Duarte', 'Nicolás Esteban Guzmán'
    );

    fecha_inicio CONSTANT DATE := DATE '2025-09-01';
    fecha_fin    CONSTANT DATE := DATE '2026-02-28';

    id_piso          PLS_INTEGER := 0;
    cantidad_pisos   PLS_INTEGER;
    piso_encontrado  NUMBER;
    id_meta          PLS_INTEGER := 0;
    fecha_meta       DATE;
    salto_dias       PLS_INTEGER;
    valor_meta       NUMBER;
    porcentaje_real  NUMBER;
    valor_real       NUMBER;
    mes_meta         PLS_INTEGER;
BEGIN
    -- 40 edificios.
    FOR id_edificio IN 1 .. edificios.COUNT LOOP
        INSERT INTO edificio (id, nombre)
        VALUES (id_edificio, edificios(id_edificio));
    END LOOP;

    -- 200 pisos: cada grupo de cinco edificios tiene 4, 5, 5, 5 y 6 pisos.
    FOR id_edificio IN 1 .. edificios.COUNT LOOP
        cantidad_pisos := CASE MOD(id_edificio, 5)
                              WHEN 1 THEN 4
                              WHEN 0 THEN 6
                              ELSE 5
                          END;

        FOR numero_piso IN 1 .. cantidad_pisos LOOP
            id_piso := id_piso + 1;
            INSERT INTO piso (id, numeropiso, idedificio)
            VALUES (id_piso, numero_piso, id_edificio);
        END LOOP;
    END LOOP;

    -- 12 cafeterias distribuidas en 10 edificios.
    FOR id_cafeteria IN 1 .. cafeterias.COUNT LOOP
        SELECT id
          INTO piso_encontrado
          FROM piso
         WHERE idedificio = edificio_cafeteria(id_cafeteria)
           AND numeropiso = piso_cafeteria(id_cafeteria);

        INSERT INTO cafeteria (id, nombre, idpiso)
        VALUES (id_cafeteria, cafeterias(id_cafeteria), piso_encontrado);
    END LOOP;

    -- 26 colaboradores: cada tercero es temporal; los demas son de planta.
    FOR id_colaborador IN 1 .. colaboradores.COUNT LOOP
        INSERT INTO colaborador (
            id, nombre, tipodocumento, numerodocumento, vinculacion, comision
        ) VALUES (
            id_colaborador,
            colaboradores(id_colaborador),
            CASE WHEN MOD(id_colaborador, 7) = 0 THEN 'CE' ELSE 'CC' END,
            10000000 + MOD(id_colaborador * 12345, 9000000),
            CASE WHEN MOD(id_colaborador, 3) = 0 THEN 'TEMPORAL' ELSE 'PLANTA' END,
            CASE MOD(id_colaborador, 4)
                WHEN 0 THEN 15
                WHEN 1 THEN 10
                WHEN 2 THEN 8
                ELSE 12
            END
        );
    END LOOP;

    -- Los colaboradores 25 y 26 quedan sin metas.
    FOR id_colaborador IN 1 .. colaboradores.COUNT LOOP
        CONTINUE WHEN id_colaborador IN (25, 26);

        FOR id_cafeteria IN 1 .. cafeterias.COUNT LOOP
            -- Los colaboradores 1 a 5 cubren todas las cafeterias.
            CONTINUE WHEN id_colaborador > 5
                      AND MOD(id_cafeteria + id_colaborador, 4) <> 0;

            salto_dias := CASE WHEN id_colaborador <= 5 THEN 24 ELSE 13 END;
            fecha_meta := fecha_inicio + MOD(id_colaborador * 3 + id_cafeteria * 5, 7);

            WHILE fecha_meta <= fecha_fin LOOP
                IF TO_CHAR(fecha_meta, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') <> 'SUN' THEN
                    valor_meta := 50000 + MOD(id_meta, 10) * 1000;
                    mes_meta := EXTRACT(MONTH FROM fecha_meta);

                    porcentaje_real := CASE
                        WHEN mes_meta IN (11, 2) THEN 75
                        WHEN mes_meta IN (9, 1)  THEN 90
                        ELSE 110
                    END;

                    valor_real := valor_meta * porcentaje_real / 100;
                    id_meta := id_meta + 1;

                    INSERT INTO meta (
                        id, fechameta, valormeta, valorreal, idcafeteria, idcolaborador
                    ) VALUES (
                        id_meta, fecha_meta, valor_meta, valor_real,
                        id_cafeteria, id_colaborador
                    );
                END IF;

                fecha_meta := fecha_meta + salto_dias;
            END LOOP;
        END LOOP;
    END LOOP;

    -- Los IDs se insertaron manualmente; se sincronizan para inserciones futuras.
    EXECUTE IMMEDIATE 'ALTER TABLE edificio MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE piso MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE cafeteria MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE colaborador MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE meta MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Poblamiento terminado:');
    DBMS_OUTPUT.PUT_LINE('  edificios    : ' || edificios.COUNT);
    DBMS_OUTPUT.PUT_LINE('  pisos        : ' || id_piso);
    DBMS_OUTPUT.PUT_LINE('  cafeterias   : ' || cafeterias.COUNT);
    DBMS_OUTPUT.PUT_LINE('  colaboradores: ' || colaboradores.COUNT);
    DBMS_OUTPUT.PUT_LINE('  metas        : ' || id_meta);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error en el poblamiento: ' || SQLERRM);
        RAISE;
END;
/

--------------------------------------------------------------------------------
-- 4. VISTAS
--------------------------------------------------------------------------------

-- Metas incumplidas y perdida monetaria.
CREATE OR REPLACE VIEW vista_1 AS
SELECT c.nombre AS colaborador,
       c.vinculacion,
       f.nombre AS cafeteria,
       e.nombre AS edificio,
       m.fechameta AS fecha_meta,
       m.valormeta AS valor_meta,
       m.valorreal AS valor_real,
       m.valormeta - m.valorreal AS perdida_monetaria
  FROM meta m
  JOIN colaborador c ON c.id = m.idcolaborador
  JOIN cafeteria f ON f.id = m.idcafeteria
  JOIN piso p ON p.id = f.idpiso
  JOIN edificio e ON e.id = p.idedificio
 WHERE m.valorreal < m.valormeta
 ORDER BY perdida_monetaria DESC, fecha_meta DESC;

-- Cantidad de cafeterias por piso, incluyendo los pisos con cero cafeterias.
CREATE OR REPLACE VIEW vista_2 AS
SELECT e.nombre AS edificio,
       p.numeropiso AS numero_piso,
       COUNT(f.id) AS total_cafeterias
  FROM edificio e
  JOIN piso p ON p.idedificio = e.id
  LEFT JOIN cafeteria f ON f.idpiso = p.id
 GROUP BY e.id, e.nombre, p.numeropiso
 ORDER BY e.nombre, p.numeropiso;

-- Comision por vinculacion y anio, mas el total general.
CREATE OR REPLACE VIEW vista_3 AS
SELECT NVL(c.vinculacion, 'TOTAL GENERAL') AS vinculacion,
       NVL(TO_CHAR(EXTRACT(YEAR FROM m.fechameta)), 'TODOS') AS anio,
       SUM(m.valorreal * c.comision / 100) AS total_comision
  FROM meta m
  JOIN colaborador c ON c.id = m.idcolaborador
 GROUP BY GROUPING SETS (
     (c.vinculacion, EXTRACT(YEAR FROM m.fechameta)),
     ()
 )
 ORDER BY GROUPING(c.vinculacion), c.vinculacion,
          EXTRACT(YEAR FROM m.fechameta);

-- Meses en los que el promedio real de la cafeteria supera su promedio meta.
CREATE OR REPLACE VIEW vista_4 AS
SELECT EXTRACT(YEAR FROM m.fechameta) AS anio,
       EXTRACT(MONTH FROM m.fechameta) AS mes,
       f.nombre AS cafeteria,
       ROUND(AVG(m.valorreal), 2) AS promedio_ventas_reales,
       ROUND(AVG(m.valormeta), 2) AS promedio_metas
  FROM meta m
  JOIN cafeteria f ON f.id = m.idcafeteria
 GROUP BY EXTRACT(YEAR FROM m.fechameta),
          EXTRACT(MONTH FROM m.fechameta),
          f.id, f.nombre
HAVING AVG(m.valorreal) > AVG(m.valormeta)
 ORDER BY anio, mes, cafeteria;

-- Colaboradores cuyo total historico supera el promedio de los totales.
CREATE OR REPLACE VIEW vista_5 AS
WITH totales AS (
    SELECT c.id,
           c.nombre,
           SUM(m.valorreal) AS total_ventas_reales
      FROM colaborador c
      JOIN meta m ON m.idcolaborador = c.id
     GROUP BY c.id, c.nombre
), promedio AS (
    SELECT AVG(total_ventas_reales) AS valor
      FROM totales
)
SELECT t.nombre AS colaborador,
       t.total_ventas_reales,
       ROUND(p.valor, 2) AS promedio_general
  FROM totales t
 CROSS JOIN promedio p
 WHERE t.total_ventas_reales > p.valor
 ORDER BY t.total_ventas_reales DESC;

-- Colaboradores presentes en todos los edificios que tienen cafeterias.
CREATE OR REPLACE VIEW vista_6 AS
SELECT c.nombre AS colaborador,
       c.numerodocumento AS numero_documento
  FROM colaborador c
  JOIN meta m ON m.idcolaborador = c.id
  JOIN cafeteria f ON f.id = m.idcafeteria
  JOIN piso p ON p.id = f.idpiso
 GROUP BY c.id, c.nombre, c.numerodocumento
HAVING COUNT(DISTINCT p.idedificio) = (
    SELECT COUNT(DISTINCT p2.idedificio)
      FROM cafeteria f2
      JOIN piso p2 ON p2.id = f2.idpiso
)
 ORDER BY c.nombre;

-- Colaboradores distintos por edificio y tipo de vinculacion.
CREATE OR REPLACE VIEW vista_7 AS
SELECT NVL(e.nombre, 'TOTALES') AS edificio,
       COUNT(DISTINCT CASE WHEN c.vinculacion = 'PLANTA' THEN c.id END)
           AS colaboradores_planta,
       COUNT(DISTINCT CASE WHEN c.vinculacion = 'TEMPORAL' THEN c.id END)
           AS colaboradores_temporales,
       COUNT(DISTINCT c.id) AS total
  FROM edificio e
  JOIN piso p ON p.idedificio = e.id
  JOIN cafeteria f ON f.idpiso = p.id
  JOIN meta m ON m.idcafeteria = f.id
  JOIN colaborador c ON c.id = m.idcolaborador
 GROUP BY GROUPING SETS ((e.id, e.nombre), ())
 ORDER BY GROUPING(e.nombre), e.nombre;

--------------------------------------------------------------------------------
-- 5. PERMISOS DE LECTURA PARA EL PROFESOR
--------------------------------------------------------------------------------
GRANT SELECT ON edificio TO JPALACIO;
GRANT SELECT ON piso TO JPALACIO;
GRANT SELECT ON cafeteria TO JPALACIO;
GRANT SELECT ON colaborador TO JPALACIO;
GRANT SELECT ON meta TO JPALACIO;

GRANT SELECT ON vista_1 TO JPALACIO;
GRANT SELECT ON vista_2 TO JPALACIO;
GRANT SELECT ON vista_3 TO JPALACIO;
GRANT SELECT ON vista_4 TO JPALACIO;
GRANT SELECT ON vista_5 TO JPALACIO;
GRANT SELECT ON vista_6 TO JPALACIO;
GRANT SELECT ON vista_7 TO JPALACIO;
