-- Script único: Creación, poblamiento, vistas y permisos (Proyecto 1)
SET DEFINE OFF
SET SERVEROUTPUT ON

-- 1. CREACIÓN DE TABLAS (DDL)
-- Borramos las tablas primero para que no salga el error ORA-00955 si el script se corre varias veces
DROP TABLE meta CASCADE CONSTRAINTS PURGE;
DROP TABLE cafeteria CASCADE CONSTRAINTS PURGE;
DROP TABLE piso CASCADE CONSTRAINTS PURGE;
DROP TABLE colaborador CASCADE CONSTRAINTS PURGE;
DROP TABLE edificio CASCADE CONSTRAINTS PURGE;

-- Creación con llaves primarias subrogadas (GENERATED BY DEFAULT AS IDENTITY)
CREATE TABLE edificio (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255)  NOT NULL,
    CONSTRAINT pk_edificio        PRIMARY KEY (id),
    CONSTRAINT uq_edificio_nombre UNIQUE (nombre)
);

CREATE TABLE piso (
    id          NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    numeropiso  NUMBER(10,0)  NOT NULL,
    idedificio  NUMBER(10,0)  NOT NULL,
    CONSTRAINT pk_piso          PRIMARY KEY (id),
    CONSTRAINT uq_piso_natural  UNIQUE (numeropiso, idedificio),
    CONSTRAINT fk_piso_edificio FOREIGN KEY (idedificio) REFERENCES edificio (id),
    CONSTRAINT ck_piso_numero   CHECK (numeropiso >= 1)
);

CREATE TABLE cafeteria (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255)  NOT NULL,
    idpiso  NUMBER(10,0)   NOT NULL,
    CONSTRAINT pk_cafeteria         PRIMARY KEY (id),
    CONSTRAINT uq_cafeteria_nombre  UNIQUE (nombre),
    CONSTRAINT fk_cafeteria_piso    FOREIGN KEY (idpiso) REFERENCES piso (id)
);

CREATE TABLE colaborador (
    id               NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(255)  NOT NULL,
    tipodocumento    VARCHAR2(255)  NOT NULL,
    numerodocumento  NUMBER(10,0)   NOT NULL,
    vinculacion      VARCHAR2(255)  NOT NULL,
    comision         NUMBER(10,0)   DEFAULT 10 NOT NULL,
    CONSTRAINT pk_colaborador          PRIMARY KEY (id),
    CONSTRAINT uq_colaborador_documento UNIQUE (tipodocumento, numerodocumento),
    CONSTRAINT ck_colaborador_vinculacion CHECK (vinculacion IN ('PLANTA', 'TEMPORAL')),
    CONSTRAINT ck_colaborador_comision    CHECK (comision BETWEEN 0 AND 100)
);

CREATE TABLE meta (
    id             NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    fechameta      DATE          NOT NULL,
    valormeta      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    valorreal      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    idcafeteria    NUMBER(10,0)  NOT NULL,
    idcolaborador  NUMBER(10,0)  NOT NULL,
    CONSTRAINT pk_meta              PRIMARY KEY (id),
    CONSTRAINT uq_meta_natural      UNIQUE (idcolaborador, idcafeteria, fechameta),
    CONSTRAINT fk_meta_cafeteria    FOREIGN KEY (idcafeteria)   REFERENCES cafeteria (id),
    CONSTRAINT fk_meta_colaborador  FOREIGN KEY (idcolaborador) REFERENCES colaborador (id),
    CONSTRAINT ck_meta_valormeta    CHECK (valormeta >= 0),
    CONSTRAINT ck_meta_valorreal    CHECK (valorreal >= 0)
);

-- Índices de apoyo para que las consultas de las vistas sean más rápidas
CREATE INDEX ix_piso_edificio      ON piso (idedificio);
CREATE INDEX ix_cafeteria_piso     ON cafeteria (idpiso);
CREATE INDEX ix_meta_cafeteria     ON meta (idcafeteria);
CREATE INDEX ix_meta_colaborador   ON meta (idcolaborador);
CREATE INDEX ix_meta_fecha         ON meta (fechameta);


-- 2. POBLAMIENTO (PL/SQL)
DECLARE
    TYPE t_texto IS TABLE OF VARCHAR2(255);
    TYPE t_numero IS TABLE OF NUMBER;

    v_edificios t_texto := t_texto(
        'Barón', 'Giraldo', 'Fernando Barón', 'Emilio Arango',
        'José Rafael Arboleda', 'Jesús María Fernández', 'Rafael Arboleda',
        'Pedro Arrupe', 'Angel Valtierra', 'Carlos Ortiz', 'Félix Restrepo',
        'Manuel Briceño', 'Gabriel Giraldo', 'Jorge Hoyos', 'Juan XXIII',
        'Rafael Barrientos', 'Luis Carlos Galán', 'Fernando Barón Norte',
        'Biblioteca Alfonso Borrero', 'Rectoría', 'Ciencias Básicas',
        'Ingeniería', 'Medicina', 'Odontología', 'Enfermería',
        'Ciencias Jurídicas', 'Ciencias Económicas', 'Comunicación y Lenguaje',
        'Filosofía', 'Teología', 'Artes', 'Psicología', 'Arquitectura',
        'Laboratorios Norte', 'Laboratorios Sur', 'Deportes', 'Bienestar',
        'Auditorio Marino Troncoso', 'Centro Ático', 'Parqueadero Central');

    v_caf_nombre t_texto := t_texto(
        'Cafetería Central', 'Cafetería Los Cerezos', 'Cafetería El Jardín',
        'Cafetería La Terraza', 'Cafetería Punto Verde', 'Cafetería Express Norte',
        'Cafetería Biblioteca', 'Cafetería Ingeniería', 'Cafetería Ingeniería 4',
        'Cafetería Medicina', 'Cafetería Deportes', 'Cafetería Ático');
    v_caf_edificio t_numero := t_numero( 1,  1,  2,  4,  6, 12, 19, 22, 22, 23, 36, 39);
    v_caf_piso     t_numero := t_numero( 1,  3,  1,  2,  1,  1,  2,  1,  4,  1,  1,  2);

    v_colaboradores t_texto := t_texto(
        'Ana María Rodríguez', 'Carlos Alberto Pérez', 'Diana Sofía Ramírez',
        'Jorge Enrique Moreno', 'Laura Catalina Gómez', 'Miguel Ángel Torres',
        'Paula Andrea Castro', 'Andrés Felipe Vargas', 'Sandra Milena Ruiz',
        'Julián David Herrera', 'Natalia Restrepo', 'Óscar Iván Suárez',
        'Claudia Patricia León', 'Ricardo Alonso Mejía', 'Mónica Alejandra Peña',
        'Fernando José Cárdenas', 'Adriana Lucía Ospina', 'Camilo Ernesto Rojas',
        'Gloria Esperanza Niño', 'Héctor Mauricio Salazar',
        'Liliana Beatriz Cortés', 'Sebastián Quintero', 'Yolanda Marcela Pineda',
        'Alejandro Bermúdez', 'Verónica Isabel Duarte', 'Nicolás Esteban Guzmán');

    c_fecha_inicio  CONSTANT DATE := DATE '2025-09-01';
    c_fecha_fin     CONSTANT DATE := DATE '2026-02-28';

    v_id_piso    PLS_INTEGER := 0;
    v_num_pisos  PLS_INTEGER;
    v_idpiso     NUMBER;
    v_id_meta    PLS_INTEGER := 0;
    v_fecha      DATE;
    v_paso       PLS_INTEGER;
    v_base       NUMBER;
    v_factor     NUMBER;
    v_real       NUMBER;
    v_mes        PLS_INTEGER;
BEGIN
    -- Limpiamos los datos actuales para evitar el error ORA-00001 (llaves duplicadas)
    DELETE FROM meta;
    DELETE FROM cafeteria;
    DELETE FROM piso;
    DELETE FROM colaborador;
    DELETE FROM edificio;

    -- Insertar los 40 edificios
    FOR i IN 1 .. v_edificios.COUNT LOOP
        INSERT INTO edificio (id, nombre) VALUES (i, v_edificios(i));
    END LOOP;

    -- Insertar pisos asegurando que la numeración inicie en 1 por cada edificio
    FOR i IN 1 .. v_edificios.COUNT LOOP
        v_num_pisos := CASE MOD(i, 5) WHEN 1 THEN 4 WHEN 0 THEN 6 ELSE 5 END;
        FOR n IN 1 .. v_num_pisos LOOP
            v_id_piso := v_id_piso + 1;
            INSERT INTO piso (id, numeropiso, idedificio)
                 VALUES (v_id_piso, n, i);
        END LOOP;
    END LOOP;

    -- Dejamos intencionalmente 30 edificios sin cafetería para cumplir el requisito
    FOR i IN 1 .. v_caf_nombre.COUNT LOOP
        SELECT id INTO v_idpiso FROM piso
         WHERE idedificio = v_caf_edificio(i) AND numeropiso = v_caf_piso(i);

        INSERT INTO cafeteria (id, nombre, idpiso)
             VALUES (i, v_caf_nombre(i), v_idpiso);
    END LOOP;

    -- Crear 26 colaboradores alternando planta y temporal
    FOR i IN 1 .. v_colaboradores.COUNT LOOP
        INSERT INTO colaborador (id, nombre, tipodocumento, numerodocumento, vinculacion, comision)
             VALUES (i,
                     v_colaboradores(i),
                     CASE WHEN MOD(i, 7) = 0 THEN 'CE' ELSE 'CC' END,
                     10000000 + MOD(i * 12345, 9000000), 
                     CASE WHEN MOD(i, 3) = 0 THEN 'TEMPORAL' ELSE 'PLANTA' END,
                     CASE MOD(i, 4) WHEN 0 THEN 15 WHEN 1 THEN 10 WHEN 2 THEN 8 ELSE 12 END);
    END LOOP;

    -- Generar los registros transaccionales de metas (más de 500 garantizados)
    FOR c IN 1 .. v_colaboradores.COUNT LOOP
        -- Los colaboradores 25 y 26 se quedan sin metas a propósito (requisito)
        CONTINUE WHEN c IN (25, 26);
        
        FOR f IN 1 .. v_caf_nombre.COUNT LOOP
            -- Los colaboradores 1 al 5 tendrán metas en TODAS las cafeterías (requisito)
            CONTINUE WHEN c > 5 AND MOD(f + c, 4) <> 0;
            v_paso  := CASE WHEN c <= 5 THEN 24 ELSE 13 END;
            v_fecha := c_fecha_inicio + MOD(c * 3 + f * 5, 7);

            WHILE v_fecha <= c_fecha_fin LOOP
                -- Filtramos para que no se asignen metas los domingos
                IF TO_CHAR(v_fecha, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') <> 'SUN' THEN
                    
                    v_base := 50000 + (MOD(v_id_meta, 10) * 1000);
                    v_mes  := EXTRACT(MONTH FROM v_fecha);

                    -- Forzamos incumplimiento general en noviembre y febrero (requisito)
                    v_factor := CASE
                                    WHEN v_mes IN (11, 2) THEN 75
                                    WHEN v_mes IN (9, 1)  THEN 90
                                    ELSE                       110
                                END;

                    v_real    := v_base * v_factor / 100;
                    v_id_meta := v_id_meta + 1;

                    INSERT INTO meta (id, fechameta, valormeta, valorreal, idcafeteria, idcolaborador)
                         VALUES (v_id_meta, v_fecha, v_base, v_real, f, c);
                END IF;
                v_fecha := v_fecha + v_paso;
            END LOOP;
        END LOOP;
    END LOOP;

    -- Actualizamos el contador de los IDENTITY para futuras inserciones
    EXECUTE IMMEDIATE 'ALTER TABLE edificio  MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE piso        MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE cafeteria   MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE colaborador MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE meta        MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Poblamiento terminado exitosamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error en el poblamiento: ' || SQLERRM);
        RAISE;
END;
/


-- 3. VISTAS SOLICITADAS

-- Vista 1: Listado de incumplimientos (filtra donde valor_real < valor_meta)
CREATE OR REPLACE VIEW vista_1 AS
SELECT col.nombre                        AS colaborador,
       col.vinculacion                   AS vinculacion,
       caf.nombre                        AS cafeteria,
       edi.nombre                        AS edificio,
       met.fechameta                     AS fecha_meta,
       met.valormeta                     AS valor_meta,
       met.valorreal                     AS valor_real,
       met.valormeta - met.valorreal     AS perdida_monetaria
  FROM meta         met
  JOIN colaborador  col ON col.id = met.idcolaborador
  JOIN cafeteria    caf ON caf.id = met.idcafeteria
  JOIN piso         pis ON pis.id = caf.idpiso
  JOIN edificio     edi ON edi.id = pis.idedificio
 WHERE met.valorreal < met.valormeta
 ORDER BY perdida_monetaria DESC, met.fechameta DESC;
/

-- Vista 2: Cobertura de infraestructura (LEFT JOIN para incluir pisos sin cafetería)
CREATE OR REPLACE VIEW vista_2 AS
SELECT edi.nombre        AS edificio,
       pis.numeropiso    AS numero_piso,
       COUNT(caf.id)     AS total_cafeterias
  FROM edificio   edi
  JOIN piso       pis ON pis.idedificio = edi.id
  LEFT JOIN cafeteria caf ON caf.idpiso = pis.id
 GROUP BY edi.id, edi.nombre, pis.numeropiso
 ORDER BY edi.nombre, pis.numeropiso;
/

-- Vista 3: Proyección de comisiones (GROUPING SETS para la fila de totales)
CREATE OR REPLACE VIEW vista_3 AS
SELECT NVL(col.vinculacion, 'TOTAL GENERAL')                       AS vinculacion,
       NVL(TO_CHAR(EXTRACT(YEAR FROM met.fechameta)), 'TODOS')     AS anio,
       SUM(met.valorreal * col.comision / 100)                     AS total_comision
  FROM meta        met
  JOIN colaborador col ON col.id = met.idcolaborador
 GROUP BY GROUPING SETS ( (col.vinculacion, EXTRACT(YEAR FROM met.fechameta)), () )
 ORDER BY GROUPING(col.vinculacion), col.vinculacion, EXTRACT(YEAR FROM met.fechameta);
/

-- Vista 4: Rendimiento mensual por cafetería (compara promedios en el HAVING)
CREATE OR REPLACE VIEW vista_4 AS
SELECT EXTRACT(YEAR  FROM met.fechameta)  AS anio,
       EXTRACT(MONTH FROM met.fechameta)  AS mes,
       caf.nombre                         AS cafeteria,
       ROUND(AVG(met.valorreal), 2)       AS promedio_ventas_reales,
       ROUND(AVG(met.valormeta), 2)       AS promedio_metas
  FROM meta      met
  JOIN cafeteria caf ON caf.id = met.idcafeteria
 GROUP BY EXTRACT(YEAR FROM met.fechameta), EXTRACT(MONTH FROM met.fechameta), caf.id, caf.nombre
HAVING AVG(met.valorreal) > AVG(met.valormeta)
 ORDER BY anio, mes, cafeteria;
/

-- Vista 5: Top de colaboradores frente al promedio general de la universidad
CREATE OR REPLACE VIEW vista_5 AS
WITH totales AS (
    SELECT col.id AS id_colaborador, col.nombre AS nombre, SUM(met.valorreal) AS total_ventas_reales
      FROM colaborador col
      JOIN meta met ON met.idcolaborador = col.id
     GROUP BY col.id, col.nombre
)
SELECT tot.nombre AS colaborador,
       tot.total_ventas_reales AS total_ventas_reales,
       (SELECT ROUND(AVG(total_ventas_reales), 2) FROM totales) AS promedio_general
  FROM totales tot
 WHERE tot.total_ventas_reales > (SELECT AVG(total_ventas_reales) FROM totales)
 ORDER BY tot.total_ventas_reales DESC;
/

-- Vista 6: Colaboradores con metas en todos los edificios (que tengan cafetería)
CREATE OR REPLACE VIEW vista_6 AS
SELECT col.nombre           AS colaborador,
       col.numerodocumento  AS numero_documento
  FROM colaborador col
  JOIN meta        met ON met.idcolaborador = col.id
  JOIN cafeteria   caf ON caf.id = met.idcafeteria
  JOIN piso        pis ON pis.id = caf.idpiso
 GROUP BY col.id, col.nombre, col.numerodocumento
HAVING COUNT(DISTINCT pis.idedificio) = ( SELECT COUNT(DISTINCT pis2.idedificio)
                                            FROM cafeteria caf2
                                            JOIN piso      pis2 ON pis2.id = caf2.idpiso )
 ORDER BY col.nombre;
/

-- Vista 7: Distribución de empleados por edificio y tipo de contrato (COUNT DISTINCT)
CREATE OR REPLACE VIEW vista_7 AS
SELECT NVL(edi.nombre, 'TOTALES')                                              AS edificio,
       COUNT(DISTINCT CASE WHEN col.vinculacion = 'PLANTA'   THEN col.id END)  AS colaboradores_planta,
       COUNT(DISTINCT CASE WHEN col.vinculacion = 'TEMPORAL' THEN col.id END)  AS colaboradores_temporales,
       COUNT(DISTINCT col.id)                                                  AS total
  FROM edificio    edi
  JOIN piso        pis ON pis.idedificio   = edi.id
  JOIN cafeteria   caf ON caf.idpiso       = pis.id
  JOIN meta        met ON met.idcafeteria  = caf.id
  JOIN colaborador col ON col.id           = met.idcolaborador
 GROUP BY GROUPING SETS ( (edi.id, edi.nombre), () )
 ORDER BY GROUPING(edi.nombre), edi.nombre;
/


-- 4. PERMISOS
-- Otorgar lectura de tablas y vistas al profesor JPALACIO
GRANT SELECT ON edificio    TO JPALACIO;
GRANT SELECT ON piso        TO JPALACIO;
GRANT SELECT ON cafeteria   TO JPALACIO;
GRANT SELECT ON colaborador TO JPALACIO;
GRANT SELECT ON meta        TO JPALACIO;

GRANT SELECT ON vista_1 TO JPALACIO;
GRANT SELECT ON vista_2 TO JPALACIO;
GRANT SELECT ON vista_3 TO JPALACIO;
GRANT SELECT ON vista_4 TO JPALACIO;
GRANT SELECT ON vista_5 TO JPALACIO;
GRANT SELECT ON vista_6 TO JPALACIO;
GRANT SELECT ON vista_7 TO JPALACIO;
