--------------------------------------------------------------------------------
-- Proyecto 1 - Bases de Datos (PUJ) - Sistema de cafeterias
-- SCRIPT UNICO DE ENTREGA: DDL + poblamiento (PL/SQL) + vistas + permisos.
-- Ejecutar completo como script (F5 en SQL Developer, @archivo en SQL*Plus).
--------------------------------------------------------------------------------
SET DEFINE OFF
SET SERVEROUTPUT ON


-- ############################ sql/01_ddl/01_crear_tablas.sql ############################

--------------------------------------------------------------------------------
-- Proyecto 1 - Bases de Datos (PUJ)
-- Sistema de cafeterias - Servicios de alimentacion PUJ
-- 01_crear_tablas.sql : DDL del esquema
-- DBMS: Oracle
--------------------------------------------------------------------------------
-- Notas de diseno:
--  * Todas las PK son subrogadas: NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY.
--  * Ningun atributo admite nulos (regla general del enunciado).
--  * Las llaves naturales se implementan como restricciones UNIQUE.
--  * fechameta se modela como DATE (el enunciado la define como "fecha diaria"
--    y las consultas 3 y 4 requieren extraer ano y mes).
--------------------------------------------------------------------------------

CREATE TABLE edificio (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255)  NOT NULL,
    CONSTRAINT pk_edificio        PRIMARY KEY (id),
    CONSTRAINT uq_edificio_nombre UNIQUE (nombre)
);

CREATE TABLE piso (
    id          NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    numeropiso  NUMBER(10,0)  NOT NULL,
    idedificio  NUMBER(10,0)  NOT NULL,
    CONSTRAINT pk_piso          PRIMARY KEY (id),
    CONSTRAINT uq_piso_natural  UNIQUE (numeropiso, idedificio),
    CONSTRAINT fk_piso_edificio FOREIGN KEY (idedificio) REFERENCES edificio (id),
    CONSTRAINT ck_piso_numero   CHECK (numeropiso >= 1)
);

CREATE TABLE cafeteria (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255)  NOT NULL,
    idpiso  NUMBER(10,0)   NOT NULL,
    CONSTRAINT pk_cafeteria         PRIMARY KEY (id),
    CONSTRAINT uq_cafeteria_nombre  UNIQUE (nombre),
    CONSTRAINT fk_cafeteria_piso    FOREIGN KEY (idpiso) REFERENCES piso (id)
);

CREATE TABLE colaborador (
    id               NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(255)  NOT NULL,
    tipodocumento    VARCHAR2(255)  NOT NULL,
    numerodocumento  NUMBER(10,0)   NOT NULL,
    vinculacion      VARCHAR2(255)  NOT NULL,
    comision         NUMBER(10,0)   DEFAULT 10 NOT NULL,
    CONSTRAINT pk_colaborador          PRIMARY KEY (id),
    CONSTRAINT uq_colaborador_documento UNIQUE (tipodocumento, numerodocumento),
    CONSTRAINT ck_colaborador_vinculacion CHECK (vinculacion IN ('PLANTA', 'TEMPORAL')),
    CONSTRAINT ck_colaborador_comision    CHECK (comision BETWEEN 0 AND 100)
);

CREATE TABLE meta (
    id             NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    fechameta      DATE          NOT NULL,
    valormeta      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    valorreal      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    idcafeteria    NUMBER(10,0)  NOT NULL,
    idcolaborador  NUMBER(10,0)  NOT NULL,
    CONSTRAINT pk_meta              PRIMARY KEY (id),
    CONSTRAINT uq_meta_natural      UNIQUE (idcolaborador, idcafeteria, fechameta),
    CONSTRAINT fk_meta_cafeteria    FOREIGN KEY (idcafeteria)   REFERENCES cafeteria (id),
    CONSTRAINT fk_meta_colaborador  FOREIGN KEY (idcolaborador) REFERENCES colaborador (id),
    CONSTRAINT ck_meta_valormeta    CHECK (valormeta >= 0),
    CONSTRAINT ck_meta_valorreal    CHECK (valorreal >= 0)
);

-- Indices de apoyo para las consultas (no exigidos, pero mejoran los joins)
CREATE INDEX ix_piso_edificio      ON piso (idedificio);
CREATE INDEX ix_cafeteria_piso     ON cafeteria (idpiso);
CREATE INDEX ix_meta_cafeteria     ON meta (idcafeteria);
CREATE INDEX ix_meta_colaborador   ON meta (idcolaborador);
CREATE INDEX ix_meta_fecha         ON meta (fechameta);

-- ############################ sql/02_dml/00_poblar_plsql.sql ############################

--------------------------------------------------------------------------------
-- Proyecto 1 - Bases de Datos (PUJ)
-- 00_poblar_plsql.sql : poblamiento COMPLETO de las 5 tablas en un solo bloque
--                       PL/SQL anonimo. No requiere herramientas externas.
--
-- Alternativa a los archivos 01_edificios.sql .. 05_metas.sql (INSERT estaticos).
-- Ejecute UNO DE LOS DOS, nunca los dos: chocarian por llave primaria.
--
-- Lineamientos del enunciado que garantiza este bloque:
--   * 40 edificios, 200 pisos (4 a 6 por edificio), 12 cafeterias, 26 colaboradores.
--   * Tabla META con mas de 500 registros sobre un periodo continuo de 6 meses
--     (2025-09-01 a 2026-02-28) que ademas cruza el cambio de ano.
--   * 30 edificios y 188 pisos quedan explicitamente sin cafeteria.
--   * Los colaboradores 1 a 5 tienen metas en absolutamente todas las cafeterias.
--   * Los colaboradores 25 y 26 no tienen ninguna meta.
--   * Noviembre 2025 y febrero 2026 son meses de incumplimiento generalizado.
--
-- DBMS_RANDOM.SEED fija la semilla: dos ejecuciones producen los mismos valores.
--------------------------------------------------------------------------------

SET DEFINE OFF
SET SERVEROUTPUT ON

DECLARE
    TYPE t_texto IS TABLE OF VARCHAR2(255);
    TYPE t_numero IS TABLE OF NUMBER;

    ---------------------------------------------------------------- catalogos
    v_edificios t_texto := t_texto(
        'Barón', 'Giraldo', 'Fernando Barón', 'Emilio Arango',
        'José Rafael Arboleda', 'Jesús María Fernández', 'Rafael Arboleda',
        'Pedro Arrupe', 'Angel Valtierra', 'Carlos Ortiz', 'Félix Restrepo',
        'Manuel Briceño', 'Gabriel Giraldo', 'Jorge Hoyos', 'Juan XXIII',
        'Rafael Barrientos', 'Luis Carlos Galán', 'Fernando Barón Norte',
        'Biblioteca Alfonso Borrero', 'Rectoría', 'Ciencias Básicas',
        'Ingeniería', 'Medicina', 'Odontología', 'Enfermería',
        'Ciencias Jurídicas', 'Ciencias Económicas', 'Comunicación y Lenguaje',
        'Filosofía', 'Teología', 'Artes', 'Psicología', 'Arquitectura',
        'Laboratorios Norte', 'Laboratorios Sur', 'Deportes', 'Bienestar',
        'Auditorio Marino Troncoso', 'Centro Ático', 'Parqueadero Central');

    -- Las 12 cafeterias y su ubicacion (edificio, numero de piso).
    -- Solo 10 edificios distintos reciben cafeteria; los otros 30 quedan vacios.
    v_caf_nombre t_texto := t_texto(
        'Cafetería Central', 'Cafetería Los Cerezos', 'Cafetería El Jardín',
        'Cafetería La Terraza', 'Cafetería Punto Verde', 'Cafetería Express Norte',
        'Cafetería Biblioteca', 'Cafetería Ingeniería', 'Cafetería Ingeniería 4',
        'Cafetería Medicina', 'Cafetería Deportes', 'Cafetería Ático');
    v_caf_edificio t_numero := t_numero( 1,  1,  2,  4,  6, 12, 19, 22, 22, 23, 36, 39);
    v_caf_piso     t_numero := t_numero( 1,  3,  1,  2,  1,  1,  2,  1,  4,  1,  1,  2);

    v_colaboradores t_texto := t_texto(
        'Ana María Rodríguez', 'Carlos Alberto Pérez', 'Diana Sofía Ramírez',
        'Jorge Enrique Moreno', 'Laura Catalina Gómez', 'Miguel Ángel Torres',
        'Paula Andrea Castro', 'Andrés Felipe Vargas', 'Sandra Milena Ruiz',
        'Julián David Herrera', 'Natalia Restrepo', 'Óscar Iván Suárez',
        'Claudia Patricia León', 'Ricardo Alonso Mejía', 'Mónica Alejandra Peña',
        'Fernando José Cárdenas', 'Adriana Lucía Ospina', 'Camilo Ernesto Rojas',
        'Gloria Esperanza Niño', 'Héctor Mauricio Salazar',
        'Liliana Beatriz Cortés', 'Sebastián Quintero', 'Yolanda Marcela Pineda',
        'Alejandro Bermúdez', 'Verónica Isabel Duarte', 'Nicolás Esteban Guzmán');

    ---------------------------------------------------------------- parametros
    c_fecha_inicio  CONSTANT DATE := DATE '2025-09-01';
    c_fecha_fin     CONSTANT DATE := DATE '2026-02-28';
    c_semilla       CONSTANT NUMBER := 20261;

    ------------------------------------------------------------------ trabajo
    v_id_piso    PLS_INTEGER := 0;
    v_num_pisos  PLS_INTEGER;
    v_idpiso     NUMBER;
    v_id_meta    PLS_INTEGER := 0;
    v_fecha      DATE;
    v_paso       PLS_INTEGER;
    v_base       NUMBER;
    v_factor     NUMBER;
    v_real       NUMBER;
    v_mes        PLS_INTEGER;
BEGIN
    DBMS_RANDOM.SEED(c_semilla);

    ----------------------------------------------------------------- EDIFICIO
    FOR i IN 1 .. v_edificios.COUNT LOOP
        INSERT INTO edificio (id, nombre) VALUES (i, v_edificios(i));
    END LOOP;

    --------------------------------------------------------------------- PISO
    -- Cantidad de pisos por edificio segun i MOD 5: 4, 5, 5, 5 o 6.
    -- El numero de piso reinicia en 1 en cada edificio, como exige el enunciado.
    FOR i IN 1 .. v_edificios.COUNT LOOP
        v_num_pisos := CASE MOD(i, 5)
                           WHEN 1 THEN 4
                           WHEN 0 THEN 6
                           ELSE 5
                       END;
        FOR n IN 1 .. v_num_pisos LOOP
            v_id_piso := v_id_piso + 1;
            INSERT INTO piso (id, numeropiso, idedificio)
                 VALUES (v_id_piso, n, i);
        END LOOP;
    END LOOP;

    ---------------------------------------------------------------- CAFETERIA
    -- El id del piso no se conoce de antemano: se resuelve por la llave natural
    -- (numeropiso, idedificio), que es justamente para lo que existe.
    FOR i IN 1 .. v_caf_nombre.COUNT LOOP
        SELECT id
          INTO v_idpiso
          FROM piso
         WHERE idedificio = v_caf_edificio(i)
           AND numeropiso = v_caf_piso(i);

        INSERT INTO cafeteria (id, nombre, idpiso)
             VALUES (i, v_caf_nombre(i), v_idpiso);
    END LOOP;

    -------------------------------------------------------------- COLABORADOR
    FOR i IN 1 .. v_colaboradores.COUNT LOOP
        INSERT INTO colaborador (id, nombre, tipodocumento, numerodocumento,
                                 vinculacion, comision)
             VALUES (i,
                     v_colaboradores(i),
                     CASE WHEN MOD(i, 7) = 0 THEN 'CE' ELSE 'CC' END,
                     1000000000 + MOD(i * 1234567, 900000000),
                     CASE WHEN MOD(i, 3) = 0 THEN 'TEMPORAL' ELSE 'PLANTA' END,
                     CASE MOD(i, 4) WHEN 0 THEN 15
                                    WHEN 1 THEN 10
                                    WHEN 2 THEN 8
                                    ELSE 12 END);
    END LOOP;

    --------------------------------------------------------------------- META
    -- Para cada par (colaborador, cafeteria) se recorre el periodo dando saltos
    -- de v_paso dias desde un desfase distinto por par. Al ser fechas
    -- estrictamente crecientes dentro de cada par, la llave natural
    -- (idcolaborador, idcafeteria, fechameta) NO se puede repetir: no hace falta
    -- verificar duplicados ni manejar DUP_VAL_ON_INDEX.
    FOR c IN 1 .. v_colaboradores.COUNT LOOP

        -- Colaboradores 25 y 26: sin ninguna meta (requisito del enunciado).
        CONTINUE WHEN c IN (25, 26);

        FOR f IN 1 .. v_caf_nombre.COUNT LOOP

            -- Colaboradores 1 a 5: cobertura total (las 12 cafeterias).
            -- El resto: solo 3 cafeterias cada uno.
            CONTINUE WHEN c > 5 AND MOD(f + c, 4) <> 0;

            -- El paso es impar a proposito: con un paso multiplo de 7 (14, 21)
            -- todas las fechas del par caerian siempre en el mismo dia de la
            -- semana y los pares que arrancaran en domingo se quedarian sin
            -- ninguna meta.
            v_paso  := CASE WHEN c <= 5 THEN 24 ELSE 13 END;
            v_fecha := c_fecha_inicio + MOD(c * 3 + f * 5, 7);

            WHILE v_fecha <= c_fecha_fin LOOP
                -- Las cafeterias no operan los domingos.
                IF TO_CHAR(v_fecha, 'D', 'NLS_TERRITORY=AMERICA') <> '1' THEN

                    v_base := (200 + TRUNC(DBMS_RANDOM.VALUE(0, 701))) * 1000;
                    v_mes  := EXTRACT(MONTH FROM v_fecha);

                    -- Noviembre y febrero: meses malos, casi todo se incumple.
                    v_factor := CASE
                                    WHEN v_mes IN (11, 2) THEN DBMS_RANDOM.VALUE(0.55, 0.95)
                                    WHEN v_mes IN (9, 1)  THEN DBMS_RANDOM.VALUE(0.70, 1.15)
                                    ELSE                       DBMS_RANDOM.VALUE(0.85, 1.35)
                                END;

                    v_real    := TRUNC(v_base * v_factor / 1000) * 1000;
                    v_id_meta := v_id_meta + 1;

                    INSERT INTO meta (id, fechameta, valormeta, valorreal,
                                      idcafeteria, idcolaborador)
                         VALUES (v_id_meta, v_fecha, v_base, v_real, f, c);
                END IF;

                v_fecha := v_fecha + v_paso;
            END LOOP;
        END LOOP;
    END LOOP;

    ------------------------------------------------- resincronizar identities
    -- Los id se insertaron de forma explicita, asi que la secuencia interna de
    -- cada columna IDENTITY sigue en 1. Se reposiciona en el maximo existente
    -- para que un INSERT posterior que omita el id no choque con la PK.
    EXECUTE IMMEDIATE 'ALTER TABLE edificio    MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE piso        MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE cafeteria   MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE colaborador MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    EXECUTE IMMEDIATE 'ALTER TABLE meta        MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Poblamiento terminado:');
    DBMS_OUTPUT.PUT_LINE('  edificios    : ' || v_edificios.COUNT);
    DBMS_OUTPUT.PUT_LINE('  pisos        : ' || v_id_piso);
    DBMS_OUTPUT.PUT_LINE('  cafeterias   : ' || v_caf_nombre.COUNT);
    DBMS_OUTPUT.PUT_LINE('  colaboradores: ' || v_colaboradores.COUNT);
    DBMS_OUTPUT.PUT_LINE('  metas        : ' || v_id_meta);

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error en el poblamiento: ' || SQLERRM);
        RAISE;
END;
/

-- ############################ sql/03_vistas/vista_1.sql ############################

--------------------------------------------------------------------------------
-- VISTA_1 - [10] Listado de incumplimientos de metas
--
-- Colaborador, vinculacion, cafeteria, edificio, fecha, meta, real y la perdida
-- monetaria (meta - real), solo para los registros donde el valor real quedo
-- estrictamente por debajo de la meta.
-- Orden: perdida descendente y luego fecha descendente.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW vista_1 AS
SELECT col.nombre                        AS colaborador,
       col.vinculacion                   AS vinculacion,
       caf.nombre                        AS cafeteria,
       edi.nombre                        AS edificio,
       met.fechameta                     AS fecha_meta,
       met.valormeta                     AS valor_meta,
       met.valorreal                     AS valor_real,
       met.valormeta - met.valorreal     AS perdida_monetaria
  FROM meta         met
  JOIN colaborador  col ON col.id = met.idcolaborador
  JOIN cafeteria    caf ON caf.id = met.idcafeteria
  JOIN piso         pis ON pis.id = caf.idpiso
  JOIN edificio     edi ON edi.id = pis.idedificio
 WHERE met.valorreal < met.valormeta
 ORDER BY perdida_monetaria DESC,
          met.fechameta     DESC;
/

-- ############################ sql/03_vistas/vista_2.sql ############################

--------------------------------------------------------------------------------
-- VISTA_2 - [10] Cobertura de infraestructura
--
-- Cantidad de cafeterias por piso. Los pisos sin cafeteria deben aparecer con 0,
-- por eso el LEFT JOIN va desde PISO hacia CAFETERIA y se cuenta caf.id (no *):
-- COUNT(*) contaria la fila del piso aunque no exista cafeteria y devolveria 1.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW vista_2 AS
SELECT edi.nombre        AS edificio,
       pis.numeropiso    AS numero_piso,
       COUNT(caf.id)     AS total_cafeterias
  FROM edificio   edi
  JOIN piso       pis ON pis.idedificio = edi.id
  LEFT JOIN cafeteria caf ON caf.idpiso = pis.id
 GROUP BY edi.id, edi.nombre, pis.numeropiso
 ORDER BY edi.nombre, pis.numeropiso;
/

-- ############################ sql/03_vistas/vista_3.sql ############################

--------------------------------------------------------------------------------
-- VISTA_3 - [10] Proyeccion de comisiones por tipo de contrato
--
-- Total a pagar por comisiones agrupado por vinculacion y ano, mas una fila
-- final con el gran total general.
--
-- La comision es un porcentaje que se paga SOBRE LAS VENTAS REALES:
--     comision = valorreal * (comision / 100)
--
-- Se usa GROUP BY GROUPING SETS y no ROLLUP: ROLLUP agregaria ademas un
-- subtotal por cada vinculacion, y el enunciado solo pide los grupos
-- (vinculacion, ano) y el gran total. GROUPING() se usa en el ORDER BY para
-- forzar que la fila del total quede de ultima.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW vista_3 AS
SELECT NVL(col.vinculacion, 'TOTAL GENERAL')                       AS vinculacion,
       NVL(TO_CHAR(EXTRACT(YEAR FROM met.fechameta)), 'TODOS')     AS anio,
       SUM(met.valorreal * col.comision / 100)                     AS total_comision
  FROM meta        met
  JOIN colaborador col ON col.id = met.idcolaborador
 GROUP BY GROUPING SETS ( (col.vinculacion, EXTRACT(YEAR FROM met.fechameta)),
                          () )
 ORDER BY GROUPING(col.vinculacion),
          col.vinculacion,
          EXTRACT(YEAR FROM met.fechameta);
/

-- ############################ sql/03_vistas/vista_4.sql ############################

--------------------------------------------------------------------------------
-- VISTA_4 - [10] Rendimiento mensual por cafeteria
--
-- Ano, mes, cafeteria y promedio de ventas reales diarias, mostrando unicamente
-- las combinaciones (cafeteria, ano, mes) donde ese promedio supero el promedio
-- de las metas propuestas para el mismo mes.
--
-- La comparacion entre los dos promedios va en HAVING porque involucra dos
-- funciones de agregacion del mismo grupo; no puede ir en WHERE.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW vista_4 AS
SELECT EXTRACT(YEAR  FROM met.fechameta)  AS anio,
       EXTRACT(MONTH FROM met.fechameta)  AS mes,
       caf.nombre                         AS cafeteria,
       ROUND(AVG(met.valorreal), 2)       AS promedio_ventas_reales,
       ROUND(AVG(met.valormeta), 2)       AS promedio_metas
  FROM meta      met
  JOIN cafeteria caf ON caf.id = met.idcafeteria
 GROUP BY EXTRACT(YEAR FROM met.fechameta),
          EXTRACT(MONTH FROM met.fechameta),
          caf.id,
          caf.nombre
HAVING AVG(met.valorreal) > AVG(met.valormeta)
 ORDER BY anio, mes, cafeteria;
/

-- ############################ sql/03_vistas/vista_5.sql ############################

--------------------------------------------------------------------------------
-- VISTA_5 - [10] Top de colaboradores sobre el promedio
--
-- Colaboradores cuyo total historico de ventas reales supera el promedio general
-- de ventas de todos los colaboradores. Se lista el nombre, su total y, como
-- tercera columna, el promedio general para poder contrastar.
--
-- Interpretacion del "promedio general": es el promedio de los TOTALES por
-- colaborador, no el promedio de los registros individuales de META. Por eso se
-- calcula primero el total de cada colaborador (CTE totales) y sobre ese
-- resultado se saca el AVG.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW vista_5 AS
WITH totales AS (
    SELECT col.id                AS id_colaborador,
           col.nombre            AS nombre,
           SUM(met.valorreal)    AS total_ventas_reales
      FROM colaborador col
      JOIN meta        met ON met.idcolaborador = col.id
     GROUP BY col.id, col.nombre
)
SELECT tot.nombre                                        AS colaborador,
       tot.total_ventas_reales                           AS total_ventas_reales,
       (SELECT ROUND(AVG(total_ventas_reales), 2) FROM totales) AS promedio_general
  FROM totales tot
 WHERE tot.total_ventas_reales > (SELECT AVG(total_ventas_reales) FROM totales)
 ORDER BY tot.total_ventas_reales DESC;
/

-- ############################ sql/03_vistas/vista_6.sql ############################

--------------------------------------------------------------------------------
-- VISTA_6 - [10] Cobertura total de edificios
--
-- Colaboradores con registros de metas en cafeterias de todos los edificios.
--
-- IMPORTANTE (decision de diseno):
-- El enunciado exige, en la seccion de insercion de datos, que existan al menos
-- dos edificios SIN ninguna cafeteria asociada. Si "todos los edificios" se
-- interpretara literalmente como los 40 registros de EDIFICIO, ningun
-- colaborador podria cumplirlo jamas (no hay cafeteria alli donde tener una
-- meta) y la vista quedaria vacia, contradiciendo la nota final "asegurese que
-- todas las consultas tengan tuplas de resultado".
--
-- Por eso el universo de comparacion son los edificios QUE TIENEN AL MENOS UNA
-- CAFETERIA: es la unica lectura bajo la cual la consulta es satisfacible.
-- La subconsulta escalar calcula ese universo de forma dinamica, sin constantes
-- quemadas, de modo que la vista sigue siendo correcta si cambian los datos.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW vista_6 AS
SELECT col.nombre           AS colaborador,
       col.tipodocumento    AS tipo_documento,
       col.numerodocumento  AS numero_documento
  FROM colaborador col
  JOIN meta        met ON met.idcolaborador = col.id
  JOIN cafeteria   caf ON caf.id = met.idcafeteria
  JOIN piso        pis ON pis.id = caf.idpiso
 GROUP BY col.id, col.nombre, col.tipodocumento, col.numerodocumento
HAVING COUNT(DISTINCT pis.idedificio) = ( SELECT COUNT(DISTINCT pis2.idedificio)
                                            FROM cafeteria caf2
                                            JOIN piso      pis2 ON pis2.id = caf2.idpiso )
 ORDER BY col.nombre;
/

-- ############################ sql/03_vistas/vista_7.sql ############################

--------------------------------------------------------------------------------
-- VISTA_7 - [20] Colaboradores por edificio y tipo de vinculacion
--
--   Edificio | Colaboradores de planta | Colaboradores temporales | Total
--   Barón    |            3            |            2             |   5
--   Giraldo  |            4            |            2             |   6
--   ...
--   Totales  |            7            |            4             |  11
--
-- Un colaborador "esta" en un edificio si tiene al menos una meta registrada en
-- alguna cafeteria ubicada en ese edificio. Se cuenta DISTINCT sobre col.id
-- porque un mismo colaborador tiene muchas metas en el mismo edificio y no debe
-- contarse varias veces.
--
-- La tabulacion cruzada se arma con COUNT(DISTINCT CASE WHEN ...): el CASE deja
-- NULL cuando la vinculacion no corresponde y COUNT ignora los NULL.
--
-- OJO con la fila de totales: al ser un COUNT DISTINCT global, un colaborador
-- que trabaja en dos edificios se cuenta UNA sola vez. Por eso la fila "TOTALES"
-- puede ser menor que la suma vertical de las filas anteriores. Es el
-- comportamiento correcto (son colaboradores distintos, no una sumatoria).
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW vista_7 AS
SELECT NVL(edi.nombre, 'TOTALES')                                              AS edificio,
       COUNT(DISTINCT CASE WHEN col.vinculacion = 'PLANTA'   THEN col.id END)  AS colaboradores_planta,
       COUNT(DISTINCT CASE WHEN col.vinculacion = 'TEMPORAL' THEN col.id END)  AS colaboradores_temporales,
       COUNT(DISTINCT col.id)                                                  AS total
  FROM edificio    edi
  JOIN piso        pis ON pis.idedificio   = edi.id
  JOIN cafeteria   caf ON caf.idpiso       = pis.id
  JOIN meta        met ON met.idcafeteria  = caf.id
  JOIN colaborador col ON col.id           = met.idcolaborador
 GROUP BY GROUPING SETS ( (edi.id, edi.nombre), () )
 ORDER BY GROUPING(edi.nombre),
          edi.nombre;
/

-- ############################ sql/04_permisos/01_grants.sql ############################

--------------------------------------------------------------------------------
-- Permisos de SELECT sobre todas las tablas y vistas para el usuario JPALACIO
-- (requisito de la seccion "DETALLES DE LA ENTREGA").
--------------------------------------------------------------------------------

-- Tablas
GRANT SELECT ON edificio    TO JPALACIO;
GRANT SELECT ON piso        TO JPALACIO;
GRANT SELECT ON cafeteria   TO JPALACIO;
GRANT SELECT ON colaborador TO JPALACIO;
GRANT SELECT ON meta        TO JPALACIO;

-- Vistas
GRANT SELECT ON vista_1 TO JPALACIO;
GRANT SELECT ON vista_2 TO JPALACIO;
GRANT SELECT ON vista_3 TO JPALACIO;
GRANT SELECT ON vista_4 TO JPALACIO;
GRANT SELECT ON vista_5 TO JPALACIO;
GRANT SELECT ON vista_6 TO JPALACIO;
GRANT SELECT ON vista_7 TO JPALACIO;

-- Verificacion de los permisos otorgados
-- SELECT grantee, table_name, privilege FROM user_tab_privs_made
--  WHERE grantee = 'JPALACIO' ORDER BY table_name;
