--------------------------------------------------------------------------------
-- Proyecto 1 - Bases de Datos (PUJ)
-- Resincronizacion de IDENTITY
-- ARCHIVO GENERADO AUTOMATICAMENTE por scripts/generar_datos.py (semilla 20261)
--------------------------------------------------------------------------------
-- Al insertar los IDs de forma explicita, la secuencia interna de una columna
-- GENERATED BY DEFAULT AS IDENTITY no avanza y quedaria en 1. Estas sentencias
-- la reposicionan en el maximo valor existente, de modo que cualquier INSERT
-- posterior que omita el id no choque contra la llave primaria.

ALTER TABLE edificio    MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE piso        MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE cafeteria   MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE colaborador MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE meta        MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));

COMMIT;
