--------------------------------------------------------------------------------
-- Proyecto 1 - Bases de Datos (PUJ)
-- Sistema de cafeterias - Servicios de alimentacion PUJ
-- 01_crear_tablas.sql : DDL del esquema
-- DBMS: Oracle
--------------------------------------------------------------------------------
-- Notas de diseno:
--  * Todas las PK son subrogadas: NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY.
--  * Ningun atributo admite nulos (regla general del enunciado).
--  * Las llaves naturales se implementan como restricciones UNIQUE.
--  * fechameta se modela como DATE (el enunciado la define como "fecha diaria"
--    y las consultas 3 y 4 requieren extraer ano y mes).
--------------------------------------------------------------------------------

CREATE TABLE edificio (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255)  NOT NULL,
    CONSTRAINT pk_edificio        PRIMARY KEY (id),
    CONSTRAINT uq_edificio_nombre UNIQUE (nombre)
);

CREATE TABLE piso (
    id          NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    numeropiso  NUMBER(10,0)  NOT NULL,
    idedificio  NUMBER(10,0)  NOT NULL,
    CONSTRAINT pk_piso          PRIMARY KEY (id),
    CONSTRAINT uq_piso_natural  UNIQUE (numeropiso, idedificio),
    CONSTRAINT fk_piso_edificio FOREIGN KEY (idedificio) REFERENCES edificio (id),
    CONSTRAINT ck_piso_numero   CHECK (numeropiso >= 1)
);

CREATE TABLE cafeteria (
    id      NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(255)  NOT NULL,
    idpiso  NUMBER(10,0)   NOT NULL,
    CONSTRAINT pk_cafeteria         PRIMARY KEY (id),
    CONSTRAINT uq_cafeteria_nombre  UNIQUE (nombre),
    CONSTRAINT fk_cafeteria_piso    FOREIGN KEY (idpiso) REFERENCES piso (id)
);

CREATE TABLE colaborador (
    id               NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(255)  NOT NULL,
    tipodocumento    VARCHAR2(255)  NOT NULL,
    numerodocumento  NUMBER(10,0)   NOT NULL,
    vinculacion      VARCHAR2(255)  NOT NULL,
    comision         NUMBER(10,0)   DEFAULT 10 NOT NULL,
    CONSTRAINT pk_colaborador          PRIMARY KEY (id),
    CONSTRAINT uq_colaborador_documento UNIQUE (tipodocumento, numerodocumento),
    CONSTRAINT ck_colaborador_vinculacion CHECK (vinculacion IN ('PLANTA', 'TEMPORAL')),
    CONSTRAINT ck_colaborador_comision    CHECK (comision BETWEEN 0 AND 100)
);

CREATE TABLE meta (
    id             NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    fechameta      DATE          NOT NULL,
    valormeta      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    valorreal      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    idcafeteria    NUMBER(10,0)  NOT NULL,
    idcolaborador  NUMBER(10,0)  NOT NULL,
    CONSTRAINT pk_meta              PRIMARY KEY (id),
    CONSTRAINT uq_meta_natural      UNIQUE (idcolaborador, idcafeteria, fechameta),
    CONSTRAINT fk_meta_cafeteria    FOREIGN KEY (idcafeteria)   REFERENCES cafeteria (id),
    CONSTRAINT fk_meta_colaborador  FOREIGN KEY (idcolaborador) REFERENCES colaborador (id),
    CONSTRAINT ck_meta_valormeta    CHECK (valormeta >= 0),
    CONSTRAINT ck_meta_valorreal    CHECK (valorreal >= 0)
);

-- Indices de apoyo para las consultas (no exigidos, pero mejoran los joins)
CREATE INDEX ix_piso_edificio      ON piso (idedificio);
CREATE INDEX ix_cafeteria_piso     ON cafeteria (idpiso);
CREATE INDEX ix_meta_cafeteria     ON meta (idcafeteria);
CREATE INDEX ix_meta_colaborador   ON meta (idcolaborador);
CREATE INDEX ix_meta_fecha         ON meta (fechameta);
